all:
	g++ -I/common tutorial03.cpp ../common/shader.cpp -o prog -L/usr/local/lib -lGL -lGLEW -lm -lglfw

run:
	./prog

brun:
	g++ -I/common tutorial03.cpp ../common/shader.cpp -o prog -L/usr/local/lib -lGL -lGLEW -lm -lglfw
	./prog
