all:
	g++ -I/common tutorial07.cpp ../common/*.cpp -o prog -L/usr/local/lib -lGL -lGLEW -lm -lglfw

run:
	./prog

brun:
	g++ -I/common tutorial07.cpp ../common/*.cpp -o prog -L/usr/local/lib -lGL -lGLEW -lm -lglfw
	./prog
