all:
	g++ -I/common tutorial01.cpp ../common/shader.cpp -o prog -L/usr/local/lib -lGL -lGLEW -lm -lglfw

run:
	./main

brun:
	g++ -I/common tutorial01.cpp ../common/shader.cpp -o prog -L/usr/local/lib -lGL -lGLEW -lm -lglfw
	./main
